spring:
  main:
    log-startup-info: false
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update  #?뚯씠釉??먮룞 ?앹꽦/?낅뜲?댄듃
    show-sql: true      #SQL 荑쇰━ 異쒕젰 (?붾쾭源낆슜)
    properties:
      hibernate:
        format_sql: true  #SQL 蹂닿린 醫뗪쾶 異쒕젰
  sql:
    init:
      mode: always  #?좏뵆由ъ??댁뀡 ?쒖옉 ??珥덇린 SQL ?ㅽ뻾
server:
  servlet:
    session:
      tracking-modes: cookie  #?몄뀡??荑좏궎濡?愿由?

